### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Ugness** [Ugness/torchdiffeq#1]
- [ ] NFE (number of function evaluation) Implementation.
- [ ] Test / Val routine.
- [ ] Visualize Bouncing ball results.
- [x] Neural Event ODE gradient check [Bug Check]
